auteur = "Mary Wollstonecraft Shelley"
author = "Mary Wollstonecraft Shelley"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/illustration.jpg"
description = "A horrific story"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo2.webp"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Revised Edition, 1831"
titre = "Frankenstein, or the Modern Prometheus"
