auteur = "Auteur"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/couverture.png"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Sous-titre"
titre = "Titre"
