auteur = "Lili Ricke"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/images/Kartoffelpflanze.jpg"
description = "Cette page informe sur l'histoire, la diversit√© et les recettes de la pomme de terre"
edition = "Lili Ricke | 2023 | CC BY-NC-SA"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/Kartoffelpflanze.jpg"
marques = "crop"
mention = "Lili Ricke"
quatrieme = "oui"
readingtime = "10 minutes"
search = false
soustitre = "ou la pomme de terre"
titre = "La Kartoffel"